In [34]:
%pip install pandas numpy matplotlib seaborn scikit-learn

Requirement already satisfied: pandas in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (3.0.6)
Requirement already satisfied: numpy in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (2.4.6)
Requirement already satisfied: matplotlib in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (3.11.2)
Requirement already satisfied: seaborn in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (0.13.2)
Requirement already satisfied: scikit-learn in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (1.9.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\hp\appdata\roaming\python\python311\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2026.4)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from matplotlib) (4.65.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from matplotlib) (1.5.1)
Requirement already satisfied: packaging>=20.0 in c:\users\hp\appdata\roaming\python\python311\site-packages (from matplotlib) (26.3)
Requirement already satisfied: pillow>=9 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from matplotlib) (12.3.0)
Requirement already satisfied: pyparsing>=3 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from matplotlib) (3.3.3)
Requirement already satisfied: scipy>=1.10.0 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.4.0 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn) (1.6.0)
Requirement already satisfied: narwhals>=2.0.1 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn) (2.26.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn) (3.7.0)
Requirement already satisfied: cloudpickle>=3.0 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from joblib>=1.4.0->scikit-learn) (3.1.2)
Requirement already satisfied: six>=1.5 in c:\users\hp\appdata\roaming\python\python311\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [35]:
import pandas as pd
import numpy as np

In [36]:
df=pd.read_csv(r"D:\My_Projects\Fifth_Project\Cryptocast\Data\Raw\bitcoin.csv")
df.head()

         Date      Price       Open       High        Low     Vol. Change %
0  24-03-2024  67,211.90  64,036.50  67,587.80  63,812.90   65.59K    4.96%
1  23-03-2024  64,037.80  63,785.60  65,972.40  63,074.90   35.11K    0.40%
2  22-03-2024  63,785.50  65,501.50  66,633.30  62,328.30   72.43K   -2.62%
3  21-03-2024  65,503.80  67,860.00  68,161.70  64,616.10   75.26K   -3.46%
4  20-03-2024  67,854.00  62,046.80  68,029.50  60,850.90  133.53K    9.35%

In [37]:
df.shape

(4999, 7)

In [38]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4999 entries, 0 to 4998
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      4999 non-null   str
 1   Price     4999 non-null   str
 2   Open      4999 non-null   str
 3   High      4999 non-null   str
 4   Low       4999 non-null   str
 5   Vol.      4993 non-null   str
 6   Change %  4999 non-null   str
dtypes: str(7)
memory usage: 273.5 KB

In [17]:
df.isnull().sum()

Date        0
Price       0
Open        0
High        0
Low         0
Vol.        6
Change %    0
dtype: int64

In [39]:
df.rename(columns={"Vol.":"Vol"},inplace=True)

In [23]:
df['Vol.'].isnull().sum()

np.int64(6)

In [33]:
def convert_vol(val):
    if pd.isna(val) or  val=="" or val=="-":
        return np.nan

    val=str(val).strip()
    suffix=val[-1]

    if suffix =="K":
        return float(val[:-1])*1000
    elif suffix =='M':
        return float(val[:-1])*1000000
    elif suffix =="B":
        return float(val[:-1])*1000000000
    else:
        return float(val)

In [44]:
df['Vol']=df['Vol'].apply(convert_vol)
df['Vol'].sample(10)

1230     93360.0
1800    782320.0
4461    218080.0
244      55730.0
4771      2740.0
2242    519400.0
4025     13940.0
4102     11760.0
2907     46950.0
801      53420.0
Name: Vol, dtype: float64

In [47]:
print("Coloumns:",df.columns.to_list())
print("NUll count in Vol columns:",df['Vol'].isnull().sum())

Coloumns: ['Date', 'Price', 'Open', 'High', 'Low', 'Vol', 'Change %']
NUll count in Vol columns: 6

In [48]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4999 entries, 0 to 4998
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      4999 non-null   str
 1   Price     4999 non-null   str
 2   Open      4999 non-null   str
 3   High      4999 non-null   str
 4   Low       4999 non-null   str
 5   Vol       4993 non-null   float64
 6   Change %  4999 non-null   str
dtypes: float64(1), str(6)
memory usage: 273.5 KB

In [52]:
df['Date']=pd.to_datetime(df['Date'], format='%d-%m-%Y')
df=df.sort_values('Date').reset_index(drop=True)

In [59]:
df[['Date','Vol']].head()
#df.info()

        Date     Vol
0 2010-07-18    80.0
1 2010-07-19   570.0
2 2010-07-20   260.0
3 2010-07-21   580.0
4 2010-07-22  2160.0

In [61]:
df.head()

        Date Price Open High  Low     Vol Change %
0 2010-07-18   0.1    0  0.1  0.1    80.0    0.00%
1 2010-07-19   0.1  0.1  0.1  0.1   570.0    0.00%
2 2010-07-20   0.1  0.1  0.1  0.1   260.0    0.00%
3 2010-07-21   0.1  0.1  0.1  0.1   580.0    0.00%
4 2010-07-22   0.1  0.1  0.1  0.1  2160.0    0.00%

In [ ]:
cols_to_clean=['Price','Open','High','Low']

for col  in cols_to_clean:
    df[col]=df[col].astype(str).str.replace(',',"").astype(float)

In [64]:
df["Change %"]=df["Change %"].astype(str).str.replace("%","").astype(float)

In [68]:
df.tail(10)

           Date    Price     Open     High      Low       Vol  Change %
4989 2024-03-15  69463.7  71387.1  72398.1  65765.6  148590.0     -2.69
4990 2024-03-16  65314.2  69456.5  70037.0  64971.0   75820.0     -5.97
4991 2024-03-17  68391.2  65314.2  68857.7  64605.5   66070.0      4.71
4992 2024-03-18  67594.1  68389.7  68920.1  66601.4   78070.0     -1.17
4993 2024-03-19  62050.0  67594.1  68099.6  61560.6  148080.0     -8.20
4994 2024-03-20  67854.0  62046.8  68029.5  60850.9  133530.0      9.35
4995 2024-03-21  65503.8  67860.0  68161.7  64616.1   75260.0     -3.46
4996 2024-03-22  63785.5  65501.5  66633.3  62328.3   72430.0     -2.62
4997 2024-03-23  64037.8  63785.6  65972.4  63074.9   35110.0      0.40
4998 2024-03-24  67211.9  64036.5  67587.8  63812.9   65590.0      4.96

In [72]:
df['Vol']=df['Vol'].ffill().bfill()

In [73]:
print("Missing values count:")
print(df.isnull().sum())

Missing values count:
Date        0
Price       0
Open        0
High        0
Low         0
Vol         0
Change %    0
dtype: int64

In [76]:
df.head()
df.columns.tolist()

['Date', 'Price', 'Open', 'High', 'Low', 'Vol', 'Change %']

In [ ]:
df=df.rename(columns={'change %':"change_pct"})
df.columns=df.columns.str.lower()

In [84]:
df.columns.tolist()

['date', 'price', 'open', 'high', 'low', 'vol', 'change_pct']

In [114]:
df.describe()

,date,price,open,high,low,vol,change_pct
count,4999,4999.000000,4999.000000,4999.000000,4999.000000,4.999000e+03,4999.000000
mean,2017-05-21 00:00:00,10812.283337,10798.901840,11067.453051,10511.891198,1.236203e+07,0.415751
min,2010-07-18 00:00:00,0.100000,0.000000,0.100000,0.000000,8.000000e+01,-57.210000
25%,2013-12-18 12:00:00,226.700000,226.450000,231.400000,221.950000,3.171000e+04,-1.170000
50%,2017-05-21 00:00:00,1975.100000,1962.000000,2048.400000,1875.300000,6.870000e+04,0.000000
75%,2020-10-21 12:00:00,15450.150000,15372.150000,15954.550000,14557.200000,1.850650e+05,1.785000
max,2024-03-24 00:00:00,73066.300000,73066.700000,73740.900000,71338.400000,4.470000e+09,336.840000
std,NaN,15892.032468,15872.785452,16270.707594,15444.928771,1.548896e+08,7.094771

In [115]:
df.to_csv("cleaned_bitcoin.csv",index=False)